### ISSUE TITLE
Don't do partial upgrades

### ISSUE THREAD

**Issue by Morganamilo** [kariudo/yay-polybar#1]
In updates-arch-yay.sh you run `yay -Sy` (essentially `pacman -Sy`) which will lead to [partial upgrades](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).

The solution is to use `yay -Qum` which will only display the upgrades for AUR packages. This can then be combined with `checkupdates` which will show repo upgrades while refreshing the database in a tmp directory.

You can combine them in a pipe with `(checkupdates; yay -Qum) | wc -l`.

**Comment by kariudo** [comment]
It should only create a risk of a partial upgrade if you synced a package without an upgrade (which personally I don't do); however, I agree using `checkupdates` for a temp copy of the database is much safer if someone with different habits was using this. I'll update this tomorrow. Thanks.
