### ISSUE TITLE
prompt-updates.sh

### ISSUE THREAD

**Issue by tuxarch** [kariudo/yay-polybar#2]
Xlib: sequence lost (0x10075 > 0x77) in reply type 0x0!
Xlib: sequence lost (0x1007a > 0x7c) in reply type 0x0!
Xlib: sequence lost (0x1007f > 0x81) in reply type 0x0!

**Comment by kariudo** [comment]
Is it not working for you, or are you just seeing these in log.

I know there are issues with extraneous output from xlib like that which can be ignored: https://bugs.archlinux.org/task/69295
